import React from 'react';
import {createRoot} from 'react-dom/client';
import {MemoryRouter, Routes, Route} from 'react-router-dom';
import WebS3 from '../src/pages/WebS3';
import {RuntimeBridge} from '../src/lib/runtime';
import {applyThemeOnBoot} from '../src/store/theme';
import {usePermissions} from '../src/store/permissions';
import {useSession} from '../src/store/session';
import '../src/styles/index.css';
if (!import.meta.env.DEV) throw Error('Development fixture only');
applyThemeOnBoot();
useSession.getState().setToken('storage-ui-fixture');
usePermissions.setState({owner:'storage-ui-fixture',loaded:true,grants:{'ai.access.use':true,'webs3.files.upload':true}});
createRoot(document.getElementById('root')!).render(<MemoryRouter initialEntries={['/webs3/101/connections/7']}><RuntimeBridge/><main style={{padding:24,height:'100%'}}><Routes><Route path="/webs3/:proxyId/connections/:credentialId/*" element={<WebS3/>}/></Routes></main></MemoryRouter>);
