import React from 'react';
import {createRoot} from 'react-dom/client';
import {MemoryRouter, Routes, Route} from 'react-router-dom';
import WebS3 from '../src/pages/WebS3';
import {RuntimeBridge} from '../src/lib/runtime';
import {applyThemeOnBoot} from '../src/store/theme';
import '../src/styles/index.css';
if (!import.meta.env.DEV) throw Error('Development fixture only');
applyThemeOnBoot();
createRoot(document.getElementById('root')!).render(<MemoryRouter initialEntries={['/webs3/101/connections/7']}><RuntimeBridge/><main style={{padding:24,height:'100%'}}><Routes><Route path="/webs3/:proxyId/connections/:credentialId/*" element={<WebS3/>}/></Routes></main></MemoryRouter>);
